"use client";

import Link from "next/link";

export default function HomePage() {
  return (
    <div className="space-y-12">
      {/* Hero */}
      <div className="text-center py-16">
        <div className="inline-flex items-center gap-2 bg-blue-50 border border-blue-200 rounded-full px-4 py-1.5 text-sm text-blue-700 font-medium mb-6">
          <span className="w-2 h-2 bg-blue-500 rounded-full animate-pulse" />
          Powered by Neo4j + Bayesian Knowledge Tracing + Gemini AI
        </div>
        <h1 className="text-5xl font-bold text-gray-900 mb-4">
          Adaptive Learning Engine
        </h1>
        <p className="text-xl text-gray-600 max-w-2xl mx-auto mb-8">
          Every assessment adapts to each student's knowledge state in real time.
          Questions are selected from the student's Zone of Proximal Development
          and generated by AI — no static question banks.
        </p>
        <div className="flex items-center justify-center gap-4">
          <Link
            href="/assessment"
            className="bg-blue-600 text-white px-8 py-3 rounded-xl font-semibold text-lg hover:bg-blue-700 transition-colors shadow-sm"
          >
            Start Assessment
          </Link>
          <Link
            href="/dashboard"
            className="bg-white text-gray-700 px-8 py-3 rounded-xl font-semibold text-lg border border-gray-200 hover:bg-gray-50 transition-colors"
          >
            View Dashboard
          </Link>
        </div>
      </div>

      {/* Feature grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {[
          {
            icon: "🧠",
            title: "BKT Mastery Tracking",
            desc: "Bayesian Knowledge Tracing updates P(mastery) after every answer. Skill states persist in Neo4j as SKILL_STATE edges.",
          },
          {
            icon: "📊",
            title: "ZPD Adaptive Selection",
            desc: "Questions are selected from the student's Zone of Proximal Development — challenging but achievable based on real skill states.",
          },
          {
            icon: "✨",
            title: "Gemini Question Generation",
            desc: "Every question is generated on-the-fly by Gemini for the exact standard, grade, state, and DOK level. No static banks.",
          },
          {
            icon: "🗺️",
            title: "Neo4j Knowledge Graph",
            desc: "242K+ StandardsFrameworkItem nodes with BUILDS_TOWARDS and DEFINES_UNDERSTANDING edges linking K1-K8 standards.",
          },
          {
            icon: "🎯",
            title: "Gap Detection",
            desc: "After each assessment, weak standards are identified and 1-2 targeted remediation exercises are generated per gap.",
          },
          {
            icon: "📈",
            title: "Grade Trajectory",
            desc: "Track mastery across all K1-K8 grades. See coverage %, mastery %, blocking gaps, and readiness scores per grade.",
          },
        ].map((f) => (
          <div key={f.title} className="bg-white rounded-2xl border border-gray-200 p-6 hover:shadow-md transition-shadow">
            <div className="text-3xl mb-3">{f.icon}</div>
            <h3 className="font-semibold text-gray-900 text-lg mb-2">{f.title}</h3>
            <p className="text-gray-600 text-sm leading-relaxed">{f.desc}</p>
          </div>
        ))}
      </div>

      {/* Quick start */}
      <div className="bg-gray-900 rounded-2xl p-8 text-white">
        <h2 className="text-2xl font-bold mb-6">Quick Start API</h2>
        <div className="space-y-4">
          <div>
            <p className="text-gray-400 text-sm mb-2">Generate an adaptive assessment:</p>
            <pre className="bg-gray-800 rounded-xl p-4 text-sm overflow-x-auto text-green-400">
{`POST /api/v1/assessment/generate
{
  "grade": "K3",
  "subject": "math",
  "student_id": "student_001",
  "state": "TX",
  "num_questions": 15
}`}
            </pre>
          </div>
          <div>
            <p className="text-gray-400 text-sm mb-2">Evaluate + get remediation exercises:</p>
            <pre className="bg-gray-800 rounded-xl p-4 text-sm overflow-x-auto text-green-400">
{`POST /api/v1/assessment/evaluate
{
  "assessment_id": "...",
  "student_id": "student_001",
  "grade": "K3", "subject": "math", "state": "TX",
  "answers": [{"node_ref":"...","is_correct":true,"category":"target",...}]
}`}
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
}
